const Appointment = require("../models/appointment.model");
const User = require("../models/user.model");
const Doctor = require("../models/doctor.model");

const createAppointment = async (data) => {
  try {
    // _id is generated by the MongoDB driver before the insert hits the server.
    // It's a random ObjectId — no counter, no sequence, no race condition possible.
    const response = await Appointment.create(data);
    return response;
  } catch (error) {
    if (error.name === "ValidationError") {
      let err = {};
      Object.keys(error.errors).forEach((key) => {
        err[key] = error.errors[key].message;
      });
      throw { err, code: 422 };
    }
    throw error;
  }
};

const getAppointments = async (data) => {
  try {
    let query = {};

    if (data?.status) query.status = data.status;
    if (data?.paymentStatus) query.paymentStatus = data.paymentStatus;

    if (data?.startDate && data?.endDate) {
      query.dateOfAppointment = {
        $gte: new Date(data.startDate),
        $lte: new Date(data.endDate),
      };
    }

    if (data?.userName) {
      const users = await User.find({
        name: { $regex: data.userName, $options: "i" },
      }).select("_id");
      query.user = { $in: users.map((u) => u._id) };
    }

    if (data?.doctorName) {
      const doctors = await Doctor.find({
        name: { $regex: data.doctorName, $options: "i" },
      }).select("_id");
      query.doctor = { $in: doctors.map((d) => d._id) };
    }

    const limit = parseInt(data?.limit) || 10;
    const page = parseInt(data?.skip) || 0;

    const response = await Appointment.find(query)
      .populate("user", "name email userRole")
      .populate("doctor")
      .populate("payment")
      .limit(limit)
      .skip(page * limit)
      .sort({ dateOfAppointment: -1 });

    const totalCount = await Appointment.countDocuments(query);

    return {
      appointments: response,
      total: totalCount,
      currentPage: page,
      totalPages: Math.ceil(totalCount / limit),
    };
  } catch (error) {
    console.error("Error in getAppointments:", error);
    throw error;
  }
};

const getAppointmentById = async (id) => {
  try {
    const response = await Appointment.findById(id)
      .populate({ path: "doctor", populate: { path: "user", select: "name" } })
      .populate("user", "name email");
    return response;
  } catch (error) {
    throw error;
  }
};

const deleteAppointment = async (id) => {
  try {
    const appointment = await Appointment.findById(id);
    if (!appointment) {
      throw { err: "Appointment not found", code: 404 };
    }
    if (appointment.paymentStatus === "PAID") {
      throw { err: "Cannot delete a paid appointment", code: 400 };
    }
    await Appointment.findByIdAndDelete(id);
    return { deleted: true };
  } catch (error) {
    throw error;
  }
};
const checkForAppointmentCount = async(doctorId, dateOfAppointment) => {
  try {
    const doctor = await Doctor.findById(doctorId);
    const count = await Appointment.countDocuments({
      doctor: doctorId,
      dateOfAppointment: dateOfAppointment,
      paymentStatus: "PAID"
    });
    return count < doctor.maxAppointmentsPerDay;
  } catch (error) {
    throw error;
  }
};

module.exports = {
  createAppointment,
  getAppointments,
  getAppointmentById,
  deleteAppointment,
  checkForAppointmentCount
};