const Appointment = require("../models/appointment.model");
const User = require("../models/user.model");
const Doctor = require("../models/doctor.model");

const createAppointment = async (data) => {
  try {
    // _id is generated by the MongoDB driver before the insert hits the server.
    // It's a random ObjectId — no counter, no sequence, no race condition possible.
    const response = await Appointment.create(data);
    return response;
  } catch (error) {
    if (error.name === "ValidationError") {
      let err = {};
      Object.keys(error.errors).forEach((key) => {
        err[key] = error.errors[key].message;
      });
      throw { err, code: 422 };
    }
    throw error;
  }
};

const getAppointments = async (data) => {
  try {
    let query = {};

    if (data?.paymentStatus) {
      query.paymentStatus = data.paymentStatus;
    }

    if (data?.userName || data?.email || data?.mob_no) {
      let userQuery = {};

      if (data?.userName) {
        userQuery.name = { $regex: data.userName, $options: "i" };
      }

      if (data?.email) {
        userQuery.email = { $regex: data.email, $options: "i" };
      }

      if (data?.mob_no) {
        userQuery.mob_no = { $regex: data.mob_no, $options: "i" };
      }

      const users = await User.find(userQuery).select("_id");

      if (users.length === 0) {
        return {
          appointments: [],
          total: 0,
          currentPage: 0,
          totalPages: 0,
        };
      }

      query.user = {
        $in: users.map((u) => u._id),
      };
    }

    if (data?.doctorName) {
      const doctorUsers = await User.find({
        name: { $regex: data.doctorName, $options: "i" },
      }).select("_id");

      const doctors = await Doctor.find({
        user: { $in: doctorUsers.map((u) => u._id) },
      }).select("_id");

      if (doctors.length === 0) {
        return {
          appointments: [],
          total: 0,
          currentPage: 0,
          totalPages: 0,
        };
      }

      query.doctor = {
        $in: doctors.map((d) => d._id),
      };
    }

    const limit = parseInt(data?.limit) || 10;
    const page = parseInt(data?.skip) || 0;

    const response = await Appointment.find(query)
      .populate("user", "name email mob_no userRole")
      .populate({
        path: "doctor",
        populate: { path: "user", select: "name email" },
      })
      .populate("payment")
      .limit(limit)
      .skip(page * limit)
      .sort({ dateOfAppointment: -1 });

    const totalCount = await Appointment.countDocuments(query);

    return {
      appointments: response,
      total: totalCount,
      currentPage: page,
      totalPages: Math.ceil(totalCount / limit),
    };
  } catch (error) {
    console.error("Error in getAppointments:", error);
    throw error;
  }
};

const getAppointmentById = async (id) => {
  try {
    const response = await Appointment.findById(id)
      .populate({ path: "doctor", populate: { path: "user", select: "name" } })
      .populate("user", "name email");
    return response;
  } catch (error) {
    throw error;
  }
};

const deleteAppointment = async (id) => {
  try {
    const appointment = await Appointment.findById(id);
    if (!appointment) {
      throw { err: "Appointment not found", code: 404 };
    }
    if (appointment.paymentStatus === "PAID") {
      throw { err: "Cannot delete a paid appointment", code: 400 };
    }
    await Appointment.findByIdAndDelete(id);
    return { deleted: true };
  } catch (error) {
    throw error;
  }
};

const checkForAppointmentCount = async (doctorId, dateOfAppointment) => {
  try {
    const doctor = await Doctor.findById(doctorId);
    const count = await Appointment.countDocuments({
      doctor: doctorId,
      dateOfAppointment: dateOfAppointment,
      paymentStatus: "PAID",
    });
    return count < doctor.maxAppointmentsPerDay;
  } catch (error) {
    throw error;
  }
};

const countAll = async () => {
  return await Appointment.countDocuments();
};

const countByStatus = async (status) => {
  return await Appointment.countDocuments({ status: status });
};

const getAppointmentsByUserID = async (userId, filters) => {
  try {
    const { paymentStatus, date } = filters;

    let query = {
      user: userId,
    };

    if (paymentStatus) {
      query.paymentStatus = paymentStatus;
    }

    // // ─── DATE FILTER ─────────────────────────────────────────
    // if (date) {

    //   const start = new Date(date);
    //   start.setHours(0, 0, 0, 0);

    //   const end = new Date(date);
    //   end.setHours(23, 59, 59, 999);

    //   query.dateOfAppointment = {
    //     $gte: start,
    //     $lte: end,
    //   };
    // }

    const appointments = await Appointment.find(query)
      .populate({
        path: "doctor",
        populate: {
          path: "user",
          select: "name email phone",
        },
      })
      .populate("payment")
      .sort({ dateOfAppointment: -1 });

    return appointments;
  } catch (error) {
    throw error;
  }
};

module.exports = {
  createAppointment,
  getAppointments,
  getAppointmentById,
  deleteAppointment,
  checkForAppointmentCount,
  countAll,
  countByStatus,
  getAppointmentsByUserID,
};
